# Generated by Django 3.0.7 on 2020-07-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.CharField(max_length=255, verbose_name='Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=255, verbose_name='Anime')),
                ('seasons', models.CharField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('realese_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.Category', verbose_name='Category')),
            ],
        ),
    ]
