# Generated by Django 3.0.7 on 2020-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_auto_20200717_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='thumb_nail',
            field=models.ImageField(default='', upload_to='anime/images'),
        ),
    ]
