# Generated by Django 3.0.7 on 2020-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_anime_thumb_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.TextField(default='', max_length='500'),
        ),
    ]
