# Generated by Django 3.0.7 on 2020-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_anime_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
    ]
