# Generated by Django 3.0.7 on 2020-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_anime_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
